### ISSUE TITLE
How to allow people without edit access to the sheet to send messages

### ISSUE THREAD

**Issue by BreadGhoti** [creme332/1bxoxb1#1]
how did you make it so people could send messages without having edit access to the sheet
![Screenshot 2024-09-06 3 25 08 PM](https://github.com/user-attachments/assets/daee8bc8-bfbd-4186-80c3-de443866d558)

**Comment by BreadGhoti** [comment]
@creme332

**Comment by creme332** [comment]
The Google Sheets which stores the message information should not be editable by the public. Only the owner of that google sheets and the App Script app has access to it. The same gmail account was used for creating the spreadsheet and deploying the App Script app. 

The chat app website itself is **not** the spreadsheet but rather the deployed version of an Apps Script app. To access the website, you should use the link of the deployed version (https://script.google.com/macros/s/AKfycbw8dbf5BvW_dXaiwgeC-7qd-wLlWdb1WSppcqP0xThBsV9JHJPYgn3EysF94OSgW4Ej/exec) instead of the link to the spreadsheet(https://docs.google.com/spreadsheets/d/1_gS0ytFOucc8YRPYsGvCOJzgx8J2SmNIA5Mz8KV03pM/edit#gid=0). To have a cleaner URL for the app, you can then embed the app as an iframe in another website like I did.

When the website is first loaded, the `getSpreadSheetData` function is executed on the server (by the App Script App) and the results are displayed on the website:

https://github.com/creme332/1bxoxb1/blob/3c68c2ecf608bbc6362fcc23b5eed5794c04a1c4/appscript/Code.gs#L36-L47

When a message is written and sent from the website, the message information is sent to the server and the `addNewRowToSheet` function is executed on the server:

https://github.com/creme332/1bxoxb1/blob/3c68c2ecf608bbc6362fcc23b5eed5794c04a1c4/appscript/Code.gs#L30-L34

**Comment by BreadGhoti** [comment]
thank you and I think I understand now and I fixed it; every time another person would open it the would get an error that stated that on line two of Code.gs they didn't have access to the Google sheets that acted as the database. I figured out that the problem was that I had it deployed as being executed by anyone instead of me specifically so I changed that and it works fully now thanks for your insight anyways!

**Comment by BreadGhoti** [comment]
also I have made a slightly more updated version. If you would like to see it just let me know. @creme332 
I have added emojis, enter to send and a different username system and I am currently working on a saving system so you have the same username each time you open it. Note: it is not my fork of your repo

**Comment by BreadGhoti** [comment]
CHECK IT OUT
https://github.com/BreadGhoti/1bxoxb1-UPDATED-

**Comment by BreadGhoti** [comment]
I hope you like my additions!

**Comment by BreadGhoti** [comment]
@creme332

**Comment by creme332** [comment]
I'm glad that you resolved your issue. Your new features look promising. Keep it up!
